// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1FupTI_D2nuylgnPMWkXtsBAhSbpKGTY',
    appId: '1:384059251194:web:32384c9d1a3aaa2a3d2c43',
    messagingSenderId: '384059251194',
    projectId: 'intelliafy',
    authDomain: 'intelliafy.firebaseapp.com',
    storageBucket: 'intelliafy.firebasestorage.app',
    measurementId: 'G-YH8WBDCSE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlEMXlAIiLsoCwIqhaH61WJpcvmHWZ6Dc',
    appId: '1:384059251194:android:d4bf69aef102aa4b3d2c43',
    messagingSenderId: '384059251194',
    projectId: 'intelliafy',
    storageBucket: 'intelliafy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPaBitVTssYOmwSoZSi0GKpsQuHj51r6k',
    appId: '1:384059251194:ios:480d1611eb4dfd563d2c43',
    messagingSenderId: '384059251194',
    projectId: 'intelliafy',
    storageBucket: 'intelliafy.firebasestorage.app',
    iosBundleId: 'com.example.intelliafyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPaBitVTssYOmwSoZSi0GKpsQuHj51r6k',
    appId: '1:384059251194:ios:480d1611eb4dfd563d2c43',
    messagingSenderId: '384059251194',
    projectId: 'intelliafy',
    storageBucket: 'intelliafy.firebasestorage.app',
    iosBundleId: 'com.example.intelliafyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1FupTI_D2nuylgnPMWkXtsBAhSbpKGTY',
    appId: '1:384059251194:web:711910284271ab553d2c43',
    messagingSenderId: '384059251194',
    projectId: 'intelliafy',
    authDomain: 'intelliafy.firebaseapp.com',
    storageBucket: 'intelliafy.firebasestorage.app',
    measurementId: 'G-JXVP32BYEQ',
  );
}
